### ISSUE TITLE
Why is there a `src/lib.rs` file with only comments?

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/polkadot-sdk-minimal-template#11] opened 2024-08-03 21:19 UTC
https://github.com/paritytech/polkadot-sdk-minimal-template/blob/master/src/lib.rs

Why does this file exist in the template?

**Comment by rzadp** [comment] 2024-08-05 10:55
These are the docs following the sentiment to [use rustdoc and keep readmes as a light intro](https://github.com/paritytech/polkadot-sdk/pull/4119#issuecomment-2074465361).
(The readme has been improved a bit since then, but `lib.rs` stayed as is).

However it doesn't quite work here because [the package](https://github.com/paritytech/polkadot-sdk/blob/master/templates/minimal/Cargo.toml) gets replaced with a workspace root. And the template crates are not published to any registry, so there is no way to read those rustdocs without cloning the repo (e.g. on mobile).

So for these reasons I think templates should be the exception and avoid rustdocs for introductory documentation, instead have it right in the readme - so we can remove `lib.rs` (or integrate into the readme file).

@gupnik Do you agree with that?

**Comment by shawntabrizi** [comment] 2024-08-05 15:59
I agree, if your auto-generation process can remove this, it makes sense to me.

**Comment by kianenigma** [comment] 2024-08-08 16:59
the only place they can be seen is in https://paritytech.github.io/polkadot-sdk/master/minimal_template/index.html

I think these were added when the template had no good readme. Now that it has, they can be removed, or bere a mere duplicate of the readme `include_str!("./README.md")`.

**Closed as completed** 2024-08-16 11:01 UTC
